# Generated by Django 5.0.4 on 2024-05-08 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.'), django.core.validators.MaxLengthValidator(254, message='Email address must be at most 254 characters long.')])),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('country', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100, message='Country name must be at most 100 characters long.')])),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100, message='City name must be at most 100 characters long.')])),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
