# Generated by Django 5.0.9 on 2024-09-19 15:10

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.'), django.core.validators.MaxLengthValidator(254, message='Email address must be at most 254 characters long.')])),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(default='EUR', max_length=3, validators=[django.core.validators.RegexValidator(message="Enter the currency code (ISO 4217), e.g., 'USD' for U.S. dollars or 'EUR' for euros", regex='^[A-Z]{3}$')])),
                ('country', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100, message='Country name must be at most 100 characters long.')])),
                ('city', models.CharField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100, message='City name must be at most 100 characters long.')])),
                ('creditToken', models.CharField(max_length=19)),
                ('clientIp', models.GenericIPAddressField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', related_query_name='donation', to='organization.organization')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
