# Generated by Django 5.0.9 on 2024-09-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='creditToken',
            field=models.CharField(max_length=1000),
        ),
    ]
