# Generated by Django 5.0.6 on 2024-05-16 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='phasesDay',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='donations', related_query_name='donation', to='organization.organization'),
            preserve_default=False,
        ),
    ]
