# Generated by Django 5.0.6 on 2024-05-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donation_phasesday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='phasesDay',
            new_name='organization',
        ),
    ]
