# Generated by Django 5.0.9 on 2024-09-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_remove_donation_clientip_remove_donation_credittoken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='stripeSessionId',
            field=models.CharField(default=' ', max_length=255, unique=True),
        ),
    ]
