# Generated by Django 5.0.6 on 2024-05-20 13:50

import django_crypto_fields.fields.encrypted_char_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_rename_phasesday_donation_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='credit_card',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text=' (Encryption: RSA local)', max_length=71),
        ),
    ]
