# Generated by Django 5.0.6 on 2024-05-20 14:10

import django_crypto_fields.fields.encrypted_char_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_donation_credit_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='credit_card',
            new_name='creditCard',
        ),
        migrations.AddField(
            model_name='donation',
            name='cardDate',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text=' (Encryption: RSA local)', max_length=71),
        ),
        migrations.AddField(
            model_name='donation',
            name='cvc',
            field=django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text=' (Encryption: RSA local)', max_length=71),
        ),
    ]
