# Generated by Django 5.0.9 on 2024-09-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_alter_donation_stripesessionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='stripeSessionId',
            field=models.CharField(default='Anonymous', max_length=255, unique=True),
        ),
    ]
