# Generated by Django 5.0.6 on 2024-05-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0005_rename_credit_card_donation_creditcard_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='creditCard',
            new_name='creditToken',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='cardDate',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='organization',
        ),
    ]
