# Generated by Django 5.0.9 on 2024-09-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0006_donation_clientip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='stripeSessionId',
            new_name='stripePaymentId',
        ),
    ]
