# Generated by Django 5.0.9 on 2024-09-25 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_rename_stripesessionid_donation_stripepaymentid'),
        ('organization', '0003_auto_20240920_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', related_query_name='donation', to='organization.organization'),
        ),
    ]
