# Generated by Django 5.0.6 on 2024-09-15 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_donation_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='status',
        ),
    ]
