# Generated by Django 5.0.9 on 2024-09-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_alter_donation_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='stripePaymentId',
            new_name='stripeSessionId',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='clientIp',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='surname',
        ),
    ]
