# Generated by Django 5.0.6 on 2024-09-15 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_remove_donation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='currency',
            field=models.CharField(default='EUR', max_length=2, validators=[django.core.validators.RegexValidator(message="Enter the currency code (ISO 4217), e.g., 'USD' for U.S. dollars or 'EUR' for euros", regex='^[A-Z]{3}$')]),
        ),
    ]
