# Generated by Django 5.0.9 on 2024-09-25 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_rename_stripepaymentid_donation_stripesessionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100, message='City name must be at most 100 characters long.')]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100, message='Country name must be at most 100 characters long.')]),
        ),
    ]
