# Generated by Django 5.0.6 on 2024-09-16 10:47

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_donation_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, validators=[django.core.validators.RegexValidator(message="Enter the currency code (ISO 4217), e.g., 'USD' for U.S. dollars or 'EUR' for euros", regex='^[A-Z]{3}$')]),
        ),
        migrations.AlterField(
            model_name='donation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
