# Generated by Django 5.0.6 on 2024-09-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_alter_donation_currency_alter_donation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='clientIp',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
