# Generated by Django 5.0.6 on 2024-09-15 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('donation', '0008_remove_donation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('receiptUrl', models.URLField(blank=True, null=True)),
                ('paymentMethod', models.CharField(blank=True, max_length=255, null=True)),
                ('clientId', models.CharField(blank=True, max_length=255, null=True)),
                ('transferId', models.CharField(blank=True, max_length=255, null=True)),
                ('amountReceived', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('applicationFee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', related_query_name='charge', to='donation.donation')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
