# Generated by Django 5.0.6 on 2024-09-15 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='clientId',
        ),
        migrations.AddField(
            model_name='charge',
            name='currency',
            field=models.CharField(default='EUR', max_length=2, validators=[django.core.validators.RegexValidator(message="Enter the currency code (ISO 4217), e.g., 'USD' for U.S. dollars or 'EUR' for euros", regex='^[A-Z]{3}$')]),
        ),
    ]
