# Generated by Django 5.0.9 on 2024-09-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='description',
            field=models.CharField(default=123, max_length=1000),
            preserve_default=False,
        ),
    ]
