# Generated by Django 5.0.9 on 2024-09-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0002_charge_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
