# Generated by Django 5.0.6 on 2024-09-16 10:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0003_alter_charge_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
