# Generated by Django 5.0.9 on 2024-09-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charges', '0003_alter_charge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='chargeId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
