# Generated by Django 5.0.9 on 2024-09-19 15:10

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=10000)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Please enter a valid email address.'), django.core.validators.MaxLengthValidator(254, message='Email address must be at most 254 characters long.')])),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Phone number must be in the correct format.', regex='^\\+?1?\\d{9,15}$')])),
                ('bankAccount', models.CharField(max_length=50)),
                ('countryCode', models.CharField(default='VA', max_length=2, validators=[django.core.validators.RegexValidator(message="Enter the country code (ISO 3166-1 alpha-2), e.g., 'US' for the United States", regex='^[A-Z]{2}$')])),
                ('currency', models.CharField(default='EUR', max_length=3, validators=[django.core.validators.RegexValidator(message="Enter the currency code (ISO 4217), e.g., 'USD' for U.S. dollars or 'EUR' for euros", regex='^[A-Z]{3}$')])),
                ('line1', models.CharField(default='Via Della Conciliazione', max_length=1000)),
                ('city', models.CharField(default='City of Vatican', max_length=50)),
                ('state', models.CharField(default='Vatican', max_length=50)),
                ('postalCode', models.CharField(default='00120', max_length=50)),
                ('web', models.CharField(default='https://www.vatican.va/', max_length=100)),
                ('stripeId', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
