# Generated by Django 5.0.9 on 2024-09-20 18:22
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [

    ]
