# Generated by Django 5.0.6 on 2024-05-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bankAccount',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
