# Generated by Django 5.0.9 on 2024-09-20 19:11
from django.core.management import call_command
from django.db import migrations

from shared.StripeUtils import create_stripe_clients


def create_organization(apps, schema_editor):
    call_command('loaddata', 'organizations.json', verbosity=0)
    create_stripe_clients()


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0002_auto_20240920_1822'),
    ]

    operations = [
        migrations.RunPython(create_organization),
    ]
