# Generated by Django 5.0.9 on 2024-09-20 19:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0002_auto_20240920_1822'),
    ]

    operations = [

    ]
