# Generated by Django 5.0.9 on 2024-09-25 08:24
from django.core.management import call_command
from django.db import migrations, models

from shared.StripeUtils import create_stripe_clients


def create_organization(apps, schema_editor):
    call_command('loaddata', 'organizations.json', verbosity=0)
    create_stripe_clients()


class Migration(migrations.Migration):
    dependencies = [
        ('organization', '0003_auto_20240920_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='project',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.RunPython(create_organization),
    ]
