# Generated by Django 5.0.6 on 2024-05-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='bankAccount',
            field=models.CharField(max_length=50),
        ),
    ]
