# Generated by Django 5.0.6 on 2024-05-16 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_bankaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='organization',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
