# Generated by Django 5.0.9 on 2024-11-11 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organization_project'),
        ('project', '0002_project_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', related_query_name='project', to='project.project'),
        ),
    ]
