# Generated by Django 5.0.6 on 2024-09-13 15:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_remove_organization_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(default='City of Vatican', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='countryCode',
            field=models.CharField(default='VA', max_length=2, validators=[django.core.validators.RegexValidator(message="Enter the country code (ISO 3166-1 alpha-2), e.g., 'US' for the United States", regex='^[A-Z]{2}$')]),
        ),
        migrations.AddField(
            model_name='organization',
            name='currency',
            field=models.CharField(default='EUR', max_length=2, validators=[django.core.validators.RegexValidator(message="Enter the currency code (ISO 4217), e.g., 'USD' for U.S. dollars or 'EUR' for euros", regex='^[A-Z]{3}$')]),
        ),
        migrations.AddField(
            model_name='organization',
            name='line1',
            field=models.CharField(default='Via Della Conciliazione', max_length=1000),
        ),
        migrations.AddField(
            model_name='organization',
            name='postalCode',
            field=models.CharField(default='00120', max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(default='Vatican', max_length=50),
        ),
    ]
