# Generated by Django 5.0.9 on 2024-11-11 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_organization_project'),
        ('project', '0004_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', related_query_name='organization', to='project.project'),
        ),
    ]
