# Generated by Django 5.0.6 on 2024-09-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organization_city_organization_countrycode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='web',
            field=models.CharField(default='https://www.vatican.va/', max_length=100),
        ),
    ]
