# Generated by Django 5.0.6 on 2024-09-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_organization_stripeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLoadFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
