# Generated by Django 5.0.6 on 2024-09-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_dataloadflag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataLoadFlag',
        ),
    ]
