# Generated by Django 5.0.9 on 2024-11-11 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='commission',
            field=models.IntegerField(default=0),
        ),
    ]
