# Generated by Django 5.0.9 on 2024-11-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='commission',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
