# Generated by Django 5.0.6 on 2024-09-16 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiErrors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apierrorlog',
            name='response_content',
        ),
        migrations.RemoveField(
            model_name='apierrorlog',
            name='response_time_ms',
        ),
    ]
